language: php

php:
    - 5.4

install:
    - composer install --no-dev --quiet -o
    - mkdir build

script:
    - ulimit -Sn 4096
    - php -dphar.readonly=0 bin/box build

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: 'build/sugarcli.phar'
    skip_cleanup: true
    on:
        tags: true
