#!/usr/bin/bash
show_help() {
cat << EOF
Usage: ${0##*/} -c [INSTANCE_NAME] [MODULE NAME]
Rewrite all email addresses in an instance so that email wont accidently go out while testing.  You
can optionally specify an email address you have control of in the second param.

    -e      Expanded Mode

example: ${0##*/} mySugarInstance Accounts
                        or
         ${0##*/} -c mySugarInstance Accounts

EOF
}

if [[ -z $1 ]]; then
    show_help
    exit 0
fi
source sugarcli.cfg
if [ $# -eq 3 ]; then
  php $sugarpath/sugarcli/bin/sugarcli hooks:list --path=$sugarpath/$2 --module=$3
else
  php $sugarpath/sugarcli/bin/sugarcli hooks:list --compact --path=$sugarpath/$1 --module=$2
fi
 
