#!/usr/bin/bash
show_help() {
cat << EOF
Usage: ${0##*/} [INSTANCE_NAME] [EMAIL_ADDRESS]
Rewrite all email addresses in an instance so that email wont accidently go out while testing.  You
can optionally specify an email address you have control of in the second param.

example: ${0##*/} mySugarInstance
                        or
         ${0##*/} mySugarInstance ken.brill.plus@gmail.com

EOF
}

if [ $# -eq 0 ]; then
    show_help
    exit 0
fi
source sugarcli.cfg
echo "Updating email addresses in $1"
if [ $# -lt 2 ]; then
  php $sugarpath/sugarcli/bin/sugarcli install:safety --path=$sugarpath/$1
else
  php $sugarpath/sugarcli/bin/sugarcli install:safety --path=$sugarpath/$1 --email=$2
fi
 
