#!/usr/bin/bash
show_help() {
cat << EOF
Usage: ${0##*/} [INSTANCE_NAME]
Resets all user passwords in an instance to 'asdf'.  Also resets
the admin user if it was repurposed or deleted.

example: ${0##*/} mySugarInstance

EOF
}
source sugarcli.cfg
if [[ -z $1 ]]; then
    show_help
    exit 0
fi
echo "Set Passwords $1"
php $sugarpath/sugarcli/bin/sugarcli system:setPasswords --path=$sugarpath/$1
 
